<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Version>0.66.0</Version>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../BetterGenshinImpact.Runtime/BetterGenshinImpact.Runtime.csproj" />
    <PackageReference Include="Microsoft.ClearScript.V8" Version="7.4.5" />
    <Compile Include="../BetterGenshinImpact/Core/Script/IScriptHost.cs" Link="IScriptHost.cs" />
    <Compile Include="../BetterGenshinImpact/Core/Script/PackageDocumentLoader.cs" Link="PackageDocumentLoader.cs" />
    <Compile Include="../BetterGenshinImpact/Core/Script/Utils/ScriptUtils.cs" Link="Utils/ScriptUtils.cs" />
    <Compile Include="../BetterGenshinImpact/Core/Script/Project/ScriptProject.cs" Link="Project/ScriptProject.cs" />
    <Compile Include="../BetterGenshinImpact/Core/Script/Project/Manifest.cs" Link="Project/Manifest.cs" />
    <Compile Include="../BetterGenshinImpact/Core/Script/Project/Author.cs" Link="Project/Author.cs" />
  </ItemGroup>
</Project>
